### ISSUE TITLE
运行就崩溃，没错误信息

### ISSUE THREAD

**Issue by ithour** [bilibili/BurstLinker#1]
试了两款手机，都是如此

**Comment by succlz123** [comment]
都是什么手机和系统版本，看下是不是磁盘权限导致的？

**Comment by ithour** [comment]
应该不是，权限崩溃会有日志的，这种没日志出来崩溃应该不是java层报出来的

在 2018-09-19 15:59:13，"Ning" <notifications@github.com> 写道：


看下是不是磁盘权限导致的？

**Comment by ithour** [comment]
三星j5   6.0.1系统

**Comment by succlz123** [comment]
试试看最新的 0.0.11

**Comment by succlz123** [comment]
试试看最新的 0.0.11

**Comment by ithour** [comment]
好的，谢谢




| |
王长健
邮箱：13871094266@163.com
|

签名由 网易邮箱大师 定制

在2018年10月22日 15:59，Ning 写道：

试试看最新的 0.0.11
