### ISSUE TITLE
Encoding GIF with Transparent background with lead to black background

### ISSUE THREAD

**Issue by objcCodingTogether** [bilibili/BurstLinker#3]
Hi ,

Thanks for the useful library.
Here is one minor issue:
When I try to encode GIF with transparent background bitmap(for example, only draw text on the canvas with transparent background) , the output GIF will have black background.
Is there any option to set the transparent background color when encoding the GIF?

Thanks in advance!

**Comment by succlz123** [comment]
Transparency is not supported at this time. I will add this feature if I have free time.:smile:

**Comment by objcCodingTogether** [comment]
Thanks for your reply!
Could you please give me some clues where should I change to support transparency? Maybe I can try to fix it and submit a pull request , and you can help to review the code.
Thanks very much!

**Comment by succlz123** [comment]
Add transparent image support, we need to enable the transparent flag of the image graphics extension control block and add the table position of the transparent color.
Look at the latest updates, give it a try.

**Comment by EricSKCheng** [comment]
Hi, 

I try the new release(0.0.11). looks like that each frame overlays the previous frame when the background is transparent.
Thanks.
