### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by dbof10** [Bilibili/BurstLinker#3]
I got a crash with message
```
java.lang.UnsatisfiedLinkError:  couldn't find "libgnustl_shared.so", "libBurstLinker.so"
```
I think the `libgnustl_shared.so` should be included inside `BurstLinker`

**Comment by succlz123** [comment]
Yes, you can try this, modify \BurstLinker\android\lib\build.gradle

~~~
arguments "-DANDROID_STL=gnustl_shared" 
~~~

👇

~~~
arguments "-DANDROID_STL=gnustl_static"
~~~

**Comment by dbof10** [comment]
I agreed. I meant I used the lib from mavenCentral. The `.so` should be included in the @aar.

**Comment by succlz123** [comment]
😃 use `com.bilibili:burst-linker:0.0.5`
