### ISSUE TITLE
Ubuntu 编译出错

### ISSUE THREAD

**Issue by watchog** [Bilibili/BurstLinker#4]
在Ubuntu 16.04 下编译，在运行命令 make BurstLinker 是报错
/home/ruanjian/git/clone/BurstLinker/src/MedianCutQuantizer.cpp: In member function ‘virtual int32_t blk::MedianCutQuantizer::quantize(blk::RGB*, uint32_t, uint32_t, blk::RGB*)’:
/home/ruanjian/git/clone/BurstLinker/src/MedianCutQuantizer.cpp:106:56: error: ‘memcpy’ was not declared in this scope
     memcpy(sortPixels, pixels, pixelCount * sizeof(RGB));

大概是MedianCutQuantizer.cpp文件缺乏 #include\<cstring\>，加入这条语句便不再报错，但是运行make BurstLinker还有问题

CMakeFiles/BurstLinker.dir/src/GifEncoder.cpp.o：在函数‘std::thread::thread<blk::ThreadPool::ThreadPool(unsigned long)::{lambda()#1}>(blk::ThreadPool::ThreadPool(unsigned long)::{lambda()#1}&&)’中：
GifEncoder.cpp:(.text._ZNSt6threadC2IZN3blk10ThreadPoolC4EmEUlvE_JEEEOT_DpOT0_[_ZNSt6threadC5IZN3blk10ThreadPoolC4EmEUlvE_JEEEOT_DpOT0_]+0x7d)：对‘pthread_create’未定义的引用

这大概是编译该文件的命令结尾未加 -lpthread （并未测试过）

**Comment by succlz123** [comment]
Add this to the CMake.txt

~~~
IF (CMAKE_SYSTEM MATCHES "Linux")
    find_package(Threads)
    target_link_libraries(BurstLinker ${CMAKE_THREAD_LIBS_INIT})
    target_link_libraries(Example ${CMAKE_THREAD_LIBS_INIT})
~~~
